export const PLANS = {
  free: {
    name: "Free",
    price: 0,
    priceId: "",
    limits: {
      pages: 1,
      aiCredits: 5,
      popups: 0,
      teamMembers: 1,
      analytics: "basic",
      heatmaps: false,
      sessionRecording: false,
      abTesting: false,
      funnels: false,
      personalization: false,
      whiteLabel: false,
      apiAccess: false,
    },
  },
  starter: {
    name: "Starter",
    price: 19,
    priceId: process.env.STRIPE_STARTER_PRICE_ID || "",
    limits: {
      pages: 15,
      aiCredits: 100,
      popups: 5,
      teamMembers: 1,
      analytics: "standard",
      heatmaps: true,
      sessionRecording: false,
      abTesting: false,
      funnels: false,
      personalization: false,
      whiteLabel: false,
      apiAccess: false,
    },
  },
  pro: {
    name: "Pro",
    price: 39,
    priceId: process.env.STRIPE_PRO_PRICE_ID || "",
    limits: {
      pages: 50,
      aiCredits: 500,
      popups: 25,
      teamMembers: 5,
      analytics: "advanced",
      heatmaps: true,
      sessionRecording: true,
      abTesting: true,
      funnels: true,
      personalization: true,
      whiteLabel: true,
      apiAccess: false,
    },
  },
  unlimited: {
    name: "Unlimited",
    price: 99,
    priceId: process.env.STRIPE_UNLIMITED_PRICE_ID || "",
    limits: {
      pages: -1, // unlimited
      aiCredits: -1,
      popups: -1,
      teamMembers: -1,
      analytics: "advanced",
      heatmaps: true,
      sessionRecording: true,
      abTesting: true,
      funnels: true,
      personalization: true,
      whiteLabel: true,
      apiAccess: true,
    },
  },
} as const;

export type PlanKey = keyof typeof PLANS;
