-- ============================================
-- Seed: 50+ Page Templates
-- ============================================

-- Landing Pages (15)
insert into public.templates (name, category, is_premium, sort_order, blocks, global_styles) values
('SaaS Starter', 'landing', false, 1, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Ship Your SaaS Faster","subheadline":"The all-in-one platform for modern startups","ctaText":"Start Free","alignment":"center"}},{"type":"features","id":"b2","content":{"heading":"Why Choose Us","layout":"grid","columns":3}},{"type":"pricing","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"cta","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#2563eb","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Agency Pro', 'landing', false, 2, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"We Build Brands That Matter","subheadline":"Full-service digital agency","ctaText":"Get a Quote","alignment":"left"}},{"type":"social-proof","id":"b2"},{"type":"features","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"cta","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#0f172a","fontFamily":"Inter","borderRadius":"0.375rem"}'),
('Product Launch', 'landing', false, 3, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Introducing the Future","subheadline":"Revolutionary product launching soon","ctaText":"Pre-order Now","alignment":"center"}},{"type":"video","id":"b2"},{"type":"features","id":"b3"},{"type":"countdown","id":"b4"},{"type":"pricing","id":"b5"},{"type":"faq","id":"b6"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#7c3aed","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('Webinar Registration', 'landing', false, 4, '[{"type":"hero","id":"b1","content":{"headline":"Free Live Webinar","subheadline":"Learn the secrets of growth marketing","ctaText":"Reserve Your Spot","alignment":"center"}},{"type":"features","id":"b2","content":{"heading":"What You Will Learn","layout":"list"}},{"type":"testimonials","id":"b3"},{"type":"countdown","id":"b4"},{"type":"form","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#dc2626","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Lead Generation', 'landing', false, 5, '[{"type":"hero","id":"b1","content":{"headline":"Get Your Free Guide","subheadline":"10 strategies to grow your business","ctaText":"Download Now","alignment":"center"}},{"type":"social-proof","id":"b2"},{"type":"features","id":"b3"},{"type":"form","id":"b4"},{"type":"testimonials","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#059669","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('App Landing', 'landing', false, 6, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Your Workflow, Simplified","subheadline":"The app that does it all","ctaText":"Download App","alignment":"left"}},{"type":"features","id":"b2"},{"type":"stats","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"pricing","id":"b5"},{"type":"faq","id":"b6"},{"type":"cta","id":"b7"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#6366f1","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('Consulting Firm', 'landing', false, 7, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Strategic Consulting for Growth","subheadline":"Expert advice for ambitious businesses","ctaText":"Book a Call","alignment":"left"}},{"type":"social-proof","id":"b2"},{"type":"features","id":"b3"},{"type":"team","id":"b4"},{"type":"testimonials","id":"b5"},{"type":"form","id":"b6"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#1e40af","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('E-commerce Promo', 'landing', true, 8, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Summer Sale — 50% Off","subheadline":"Limited time only","ctaText":"Shop Now","alignment":"center"}},{"type":"countdown","id":"b2"},{"type":"gallery","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"cta","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#e11d48","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Newsletter Signup', 'landing', false, 9, '[{"type":"hero","id":"b1","content":{"headline":"Stay in the Loop","subheadline":"Weekly insights delivered to your inbox","ctaText":"Subscribe","alignment":"center"}},{"type":"features","id":"b2","content":{"heading":"What You Get","layout":"list"}},{"type":"testimonials","id":"b3"},{"type":"form","id":"b4"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#8b5cf6","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('Course Enrollment', 'landing', true, 10, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Master Digital Marketing","subheadline":"12-week intensive course","ctaText":"Enroll Now","alignment":"center"}},{"type":"video","id":"b2"},{"type":"features","id":"b3","content":{"heading":"Course Modules","layout":"list"}},{"type":"testimonials","id":"b4"},{"type":"pricing","id":"b5"},{"type":"faq","id":"b6"},{"type":"form","id":"b7"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#0891b2","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Startup Pitch', 'landing', true, 11, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"The Future of Finance","subheadline":"AI-powered financial management","ctaText":"Join Waitlist","alignment":"center"}},{"type":"stats","id":"b2"},{"type":"features","id":"b3"},{"type":"comparison","id":"b4"},{"type":"testimonials","id":"b5"},{"type":"team","id":"b6"},{"type":"cta","id":"b7"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#0d9488","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('Freelancer Portfolio', 'landing', false, 12, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Hi, I am Jane","subheadline":"UI/UX Designer & Developer","ctaText":"Hire Me","alignment":"left"}},{"type":"gallery","id":"b2"},{"type":"testimonials","id":"b3"},{"type":"features","id":"b4","content":{"heading":"Services","layout":"grid"}},{"type":"form","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#ec4899","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('Real Estate', 'landing', true, 13, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Find Your Dream Home","subheadline":"Premium real estate listings","ctaText":"Browse Listings","alignment":"center"}},{"type":"features","id":"b2"},{"type":"gallery","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"form","id":"b5","content":{"heading":"Schedule a Viewing"}},{"type":"footer","id":"f1"}]', '{"primaryColor":"#b45309","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Health & Fitness', 'landing', true, 14, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Transform Your Body","subheadline":"Personal training that works","ctaText":"Start Today","alignment":"center"}},{"type":"stats","id":"b2"},{"type":"features","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"pricing","id":"b5"},{"type":"form","id":"b6"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#16a34a","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Event Landing', 'landing', true, 15, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Tech Conference 2026","subheadline":"October 15-17, San Francisco","ctaText":"Get Tickets","alignment":"center"}},{"type":"countdown","id":"b2"},{"type":"features","id":"b3","content":{"heading":"Speakers","layout":"grid"}},{"type":"video","id":"b4"},{"type":"pricing","id":"b5"},{"type":"faq","id":"b6"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#9333ea","fontFamily":"Inter","borderRadius":"0.75rem"}');

-- Product / Service Pages (10)
insert into public.templates (name, category, is_premium, sort_order, blocks, global_styles) values
('Product Showcase', 'product', false, 20, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2"},{"type":"gallery","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"pricing","id":"b5"},{"type":"cta","id":"b6"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#2563eb","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Service Overview', 'product', false, 21, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2"},{"type":"stats","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"form","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#0f172a","fontFamily":"Inter","borderRadius":"0.375rem"}'),
('Digital Product', 'product', true, 22, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"video","id":"b2"},{"type":"features","id":"b3"},{"type":"comparison","id":"b4"},{"type":"testimonials","id":"b5"},{"type":"pricing","id":"b6"},{"type":"faq","id":"b7"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#7c3aed","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('API Documentation', 'product', true, 23, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Powerful API","subheadline":"Build anything with our API"}},{"type":"features","id":"b2"},{"type":"tabs","id":"b3"},{"type":"pricing","id":"b4"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#059669","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('SaaS Features', 'product', false, 24, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2"},{"type":"comparison","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"cta","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#6366f1","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Restaurant Menu', 'product', true, 25, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Fine Dining Experience"}},{"type":"gallery","id":"b2"},{"type":"tabs","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"form","id":"b5","content":{"heading":"Make a Reservation"}},{"type":"footer","id":"f1"}]', '{"primaryColor":"#92400e","fontFamily":"Inter","borderRadius":"0.375rem"}'),
('Salon & Spa', 'product', true, 26, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2","content":{"heading":"Our Services"}},{"type":"gallery","id":"b3"},{"type":"pricing","id":"b4"},{"type":"testimonials","id":"b5"},{"type":"form","id":"b6"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#be185d","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('Fitness Studio', 'product', true, 27, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2"},{"type":"stats","id":"b3"},{"type":"pricing","id":"b4"},{"type":"testimonials","id":"b5"},{"type":"cta","id":"b6"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#ea580c","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Law Firm', 'product', true, 28, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Justice You Can Trust"}},{"type":"features","id":"b2"},{"type":"team","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"form","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#1e3a5f","fontFamily":"Inter","borderRadius":"0.375rem"}'),
('Dental Clinic', 'product', true, 29, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2","content":{"heading":"Our Services"}},{"type":"team","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"form","id":"b5","content":{"heading":"Book an Appointment"}},{"type":"footer","id":"f1"}]', '{"primaryColor":"#0284c7","fontFamily":"Inter","borderRadius":"0.5rem"}');

-- Coming Soon (5)
insert into public.templates (name, category, is_premium, sort_order, blocks, global_styles) values
('Minimal Coming Soon', 'coming-soon', false, 40, '[{"type":"hero","id":"b1","content":{"headline":"Something Amazing is Coming","subheadline":"Be the first to know","ctaText":"Notify Me","alignment":"center"}},{"type":"countdown","id":"b2"},{"type":"form","id":"b3"}]', '{"primaryColor":"#18181b","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Product Teaser', 'coming-soon', false, 41, '[{"type":"hero","id":"b1","content":{"headline":"Launching Soon","subheadline":"A revolutionary new product"}},{"type":"countdown","id":"b2"},{"type":"features","id":"b3","content":{"heading":"Sneak Peek"}},{"type":"form","id":"b4"}]', '{"primaryColor":"#7c3aed","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('App Teaser', 'coming-soon', true, 42, '[{"type":"hero","id":"b1"},{"type":"video","id":"b2"},{"type":"countdown","id":"b3"},{"type":"form","id":"b4"},{"type":"social-proof","id":"b5"}]', '{"primaryColor":"#2563eb","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('Event Countdown', 'coming-soon', true, 43, '[{"type":"hero","id":"b1","content":{"headline":"The Big Event"}},{"type":"countdown","id":"b2"},{"type":"features","id":"b3","content":{"heading":"What to Expect"}},{"type":"form","id":"b4"}]', '{"primaryColor":"#dc2626","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Brand Launch', 'coming-soon', true, 44, '[{"type":"hero","id":"b1"},{"type":"video","id":"b2"},{"type":"countdown","id":"b3"},{"type":"form","id":"b4"}]', '{"primaryColor":"#0f172a","fontFamily":"Inter","borderRadius":"0.375rem"}');

-- Portfolio (5)
insert into public.templates (name, category, is_premium, sort_order, blocks, global_styles) values
('Creative Portfolio', 'portfolio', false, 50, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Creative Designer","alignment":"left"}},{"type":"gallery","id":"b2"},{"type":"testimonials","id":"b3"},{"type":"form","id":"b4"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#ec4899","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('Developer Portfolio', 'portfolio', false, 51, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2","content":{"heading":"Tech Stack"}},{"type":"gallery","id":"b3","content":{"heading":"Projects"}},{"type":"testimonials","id":"b4"},{"type":"form","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#22c55e","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Photography', 'portfolio', true, 52, '[{"type":"hero","id":"b1","content":{"headline":"Visual Storytelling"}},{"type":"gallery","id":"b2"},{"type":"testimonials","id":"b3"},{"type":"form","id":"b4"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#0f172a","fontFamily":"Inter","borderRadius":"0rem"}'),
('Agency Portfolio', 'portfolio', true, 53, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"logo-carousel","id":"b2"},{"type":"gallery","id":"b3"},{"type":"stats","id":"b4"},{"type":"team","id":"b5"},{"type":"testimonials","id":"b6"},{"type":"cta","id":"b7"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#1e40af","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Architect Portfolio', 'portfolio', true, 54, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"gallery","id":"b2"},{"type":"features","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"form","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#78716c","fontFamily":"Inter","borderRadius":"0rem"}');

-- Event / Webinar (5)
insert into public.templates (name, category, is_premium, sort_order, blocks, global_styles) values
('Conference', 'event', false, 60, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"countdown","id":"b2"},{"type":"features","id":"b3","content":{"heading":"Speakers"}},{"type":"pricing","id":"b4"},{"type":"faq","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#7c3aed","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('Workshop', 'event', false, 61, '[{"type":"hero","id":"b1","content":{"headline":"Hands-on Workshop"}},{"type":"features","id":"b2"},{"type":"testimonials","id":"b3"},{"type":"form","id":"b4"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#0891b2","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Meetup', 'event', true, 62, '[{"type":"hero","id":"b1"},{"type":"countdown","id":"b2"},{"type":"features","id":"b3"},{"type":"form","id":"b4"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#e11d48","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Charity Gala', 'event', true, 63, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"stats","id":"b2"},{"type":"gallery","id":"b3"},{"type":"form","id":"b4"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#b45309","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Virtual Summit', 'event', true, 64, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"countdown","id":"b2"},{"type":"features","id":"b3"},{"type":"video","id":"b4"},{"type":"pricing","id":"b5"},{"type":"faq","id":"b6"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#6366f1","fontFamily":"Inter","borderRadius":"0.75rem"}');

-- Local Business (5)
insert into public.templates (name, category, is_premium, sort_order, blocks, global_styles) values
('Local Business', 'local', false, 70, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2"},{"type":"testimonials","id":"b3"},{"type":"form","id":"b4"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#2563eb","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Coffee Shop', 'local', true, 71, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1","content":{"headline":"Freshly Brewed"}},{"type":"gallery","id":"b2"},{"type":"features","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"form","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#78350f","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('Auto Repair', 'local', true, 72, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2","content":{"heading":"Our Services"}},{"type":"testimonials","id":"b3"},{"type":"form","id":"b4"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#dc2626","fontFamily":"Inter","borderRadius":"0.375rem"}'),
('Pet Care', 'local', true, 73, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2"},{"type":"gallery","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"pricing","id":"b5"},{"type":"form","id":"b6"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#f59e0b","fontFamily":"Inter","borderRadius":"0.75rem"}'),
('Cleaning Service', 'local', true, 74, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2"},{"type":"pricing","id":"b3"},{"type":"testimonials","id":"b4"},{"type":"form","id":"b5"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#0d9488","fontFamily":"Inter","borderRadius":"0.5rem"}');

-- Blank / Minimal (5)
insert into public.templates (name, category, is_premium, sort_order, blocks, global_styles) values
('Blank Canvas', 'blank', false, 80, '[]', '{"primaryColor":"#2563eb","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Header + Hero', 'blank', false, 81, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#2563eb","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Simple Lead Gen', 'blank', false, 82, '[{"type":"hero","id":"b1"},{"type":"form","id":"b2"}]', '{"primaryColor":"#2563eb","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Minimal Dark', 'blank', false, 83, '[{"type":"hero","id":"b1"},{"type":"features","id":"b2"},{"type":"cta","id":"b3"}]', '{"primaryColor":"#e2e8f0","fontFamily":"Inter","borderRadius":"0.5rem"}'),
('Full Structure', 'blank', false, 84, '[{"type":"header","id":"h1"},{"type":"hero","id":"b1"},{"type":"features","id":"b2"},{"type":"testimonials","id":"b3"},{"type":"pricing","id":"b4"},{"type":"faq","id":"b5"},{"type":"cta","id":"b6"},{"type":"footer","id":"f1"}]', '{"primaryColor":"#2563eb","fontFamily":"Inter","borderRadius":"0.5rem"}');
